# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bag_predict <- function(coords_tr, coords_pred, ptts_pred, idx_pred, pptts_pred_list, w_save, psi_save, sigsq_save, tausq_save, num_threads = 4L, verbose = FALSE) {
    .Call(`_bags_bag_predict`, coords_tr, coords_pred, ptts_pred, idx_pred, pptts_pred_list, w_save, psi_save, sigsq_save, tausq_save, num_threads, verbose)
}

createRnH <- function(coords, idx, pptts_list, ptts_proto, a, c, kappa, produce_R, directions) {
    .Call(`_bags_createRnH`, coords, idx, pptts_list, ptts_proto, a, c, kappa, produce_R, directions)
}

wsigupdate <- function(res, w, sig_sq, tau_sq, z, RnH_list, ptts, idx, pptts_list, ptts_proto, nd, as, bs) {
    .Call(`_bags_wsigupdate`, res, w, sig_sq, tau_sq, z, RnH_list, ptts, idx, pptts_list, ptts_proto, nd, as, bs)
}

zupdate <- function(pi_i, w, sig_sq, RnH_list, ptts, idx, pptts_list, ptts_proto, nd, directions) {
    .Call(`_bags_zupdate`, pi_i, w, sig_sq, RnH_list, ptts, idx, pptts_list, ptts_proto, nd, directions)
}

psiupdate <- function(w, z, sig_sq, theta, Sn, invS, RnH_list, coords, idx, pptts_list, ptts_proto, ptts, nd, iter, adaptive, unifprior, directions) {
    .Call(`_bags_psiupdate`, w, z, sig_sq, theta, Sn, invS, RnH_list, coords, idx, pptts_list, ptts_proto, ptts, nd, iter, adaptive, unifprior, directions)
}

isin <- function(m, ptts_proto) {
    .Call(`_bags_isin`, m, ptts_proto)
}

str_split <- function(str, delim) {
    .Call(`_bags_str_split`, str, delim)
}

concatenate <- function(x, z, nd) {
    .Call(`_bags_concatenate`, x, z, nd)
}

findchild <- function(m, z_ptt, ptts) {
    .Call(`_bags_findchild`, m, z_ptt, ptts)
}

negidxing <- function(a, A) {
    .Call(`_bags_negidxing`, a, A)
}

distmat_Euclidean <- function(A) {
    .Call(`_bags_distmat_Euclidean`, A)
}

distmat_abs <- function(A) {
    .Call(`_bags_distmat_abs`, A)
}

